### ISSUE TITLE
Getting execute_cdp_cmd error

### ISSUE THREAD

**Issue by dkjha52** [alumnium-hq/alumnium#11]
execute_cdp_cmd is not working for remote web driver.

Here is the error message - AttributeError: 'WebDriver' object has no attribute 'execute_cdp_cmd'

**Comment by p0deje** [comment]
Do you use Chrome/Edge with the remote WebDriver, or a different browser?

**Comment by dkjha52** [comment]
Yes. I am using Chrome remote WebDriver

**Comment by p0deje** [comment]
The problem could be that Selenium only exposes the `execute_cdp_cmd` method on _local_ drivers, not _remote_. I'll investigate and get back to you.

**Comment by p0deje** [comment]
Please try using 0.3.0 and let me know if it works!

**Comment by dkjha52** [comment]
Yes. Its working fine. Thanks. However it gives the below warning message -
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1732776810.702445 5115107 init.cc:229] grpc_wait_for_shutdown_with_timeout() timed out.

**Comment by p0deje** [comment]
Warnings are unfortunate, but at least it's working now!
