### ISSUE TITLE
Unable to check checkbox

### ISSUE THREAD

**Issue by dkjha52** [alumnium-hq/alumnium#14]
Here is the error - E   selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input type="checkbox" id="terms" name="terms" value="1" required=""> is not clickable at point (615, 727). Other element would receive the click: <span class="form_tos">...</span>
Please provide sample statement to check the checkbox

**Comment by p0deje** [comment]
We have some tests demonstrating that checkbox selection via click works - https://github.com/alumnium-hq/alumnium/blob/main/examples/behave/features/todo.feature
Can you provide a test case to reproduce the issue?

**Comment by dkjha52** [comment]
Here is the page source of the checkbox element. I tried but not working - 
<label class="checkbox__container checkbox__container-new" for="00N040000056700">
          	<input type="checkbox" id="00N040000056700" name="00N040000056700" value="1" xpath="1">
          	<span>
          		::before
          		I agree to receive emails from company.
          	</span>
        </label>

**Comment by p0deje** [comment]
I need something more than just HTML code to reproduce. Ideally, can you provide the Python script that I could run to have the same failure?

**Comment by p0deje** [comment]
Closing since there is no response.
